#jar?? ??? ? --spring.profiles.active=dev ??? ??? ?
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:postgresql://localhost:5432/lifetail"
    username: "chamchi"
    password: "159357"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #jpa? ??? ??? ???? ??? ??? ???
      ddl-auto: none
    properties:
      hibernate:
        #JPA? ??? DB? SQL? ?? ? SQL? ??? ????
        show_sql: true
        #JPA? ??? DB? SQL? ???? ??? ? ? ??? ??? ?? ? ???
        format_sql: true
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/lifetail"
#    username: "chamchi"
#    password: "159357"
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      #jpa? ??? ??? ???? ??? ??? ???
#      ddl-auto: none
#    properties:
#      hibernate:
#        #JPA? ??? DB? SQL? ?? ? SQL? ??? ????
#        show_sql: true
#        #JPA? ??? DB? SQL? ???? ??? ? ? ??? ??? ?? ? ???
#        format_sql: true